// actionTypes.js
export const CREATE_TOOL_REQUEST = 'CREATE_TOOL_REQUEST';
export const CREATE_TOOL_SUCCESS = 'CREATE_TOOL_SUCCESS';
export const CREATE_TOOL_FAILURE = 'CREATE_TOOL_FAILURE';

export const GET_TOOL_REQUEST = 'GET_TOOL_REQUEST';
export const GET_TOOL_SUCCESS = 'GET_TOOL_SUCCESS';
export const GET_TOOL_FAILURE = 'GET_TOOL_FAILURE';

export const GET_ALL_TOOLS_REQUEST = 'GET_ALL_TOOLS_REQUEST';
export const GET_ALL_TOOLS_SUCCESS = 'GET_ALL_TOOLS_SUCCESS';
export const GET_ALL_TOOLS_FAILURE = 'GET_ALL_TOOLS_FAILURE';

export const UPDATE_TOOL_REQUEST = 'UPDATE_TOOL_REQUEST';
export const UPDATE_TOOL_SUCCESS = 'UPDATE_TOOL_SUCCESS';
export const UPDATE_TOOL_FAILURE = 'UPDATE_TOOL_FAILURE';

export const DELETE_TOOL_REQUEST = 'DELETE_TOOL_REQUEST';
export const DELETE_TOOL_SUCCESS = 'DELETE_TOOL_SUCCESS';
export const DELETE_TOOL_FAILURE = 'DELETE_TOOL_FAILURE';
