// actionTypes.js
export const CREATE_FILES_REQUEST = 'CREATE_FILES_REQUEST';
export const CREATE_FILES_SUCCESS = 'CREATE_FILES_SUCCESS';
export const CREATE_FILES_FAILURE = 'CREATE_FILES_FAILURE';

export const GET_FILES_REQUEST = 'GET_FILES_REQUEST';
export const GET_FILES_SUCCESS = 'GET_FILES_SUCCESS';
export const GET_FILES_FAILURE = 'GET_FILES_FAILURE';

export const GET_ALL_FILES_REQUEST = 'GET_ALL_FILES_REQUEST';
export const GET_ALL_FILES_SUCCESS = 'GET_ALL_FILES_SUCCESS';
export const GET_ALL_FILES_FAILURE = 'GET_ALL_FILES_FAILURE';

export const UPDATE_FILES_REQUEST = 'UPDATE_FILES_REQUEST';
export const UPDATE_FILES_SUCCESS = 'UPDATE_FILES_SUCCESS';
export const UPDATE_FILES_FAILURE = 'UPDATE_FILES_FAILURE';

export const DELETE_FILES_REQUEST = 'DELETE_FILES_REQUEST';
export const DELETE_FILES_SUCCESS = 'DELETE_FILES_SUCCESS';
export const DELETE_FILES_FAILURE = 'DELETE_FILES_FAILURE';

export const FIND_FILES_BY_COMPANY_ID_REQUEST = 'FIND_FILES_BY_COMPANY_ID_REQUEST';
export const FIND_FILES_BY_COMPANY_ID_SUCCESS = 'FIND_FILES_BY_COMPANY_ID_SUCCESS';
export const FIND_FILES_BY_COMPANY_ID_FAILURE = 'FIND_FILES_BY_COMPANY_ID_FAILURE';
